[package]
name = "pic16f8x_emu"
version = "0.1.0"
authors = ["Jan Lafferton <jla@jcbachmann.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
