[package]
name = "pic16f8x_emu"
version = "0.1.0"
authors = ["Jan Lafferton <jla@jcbachmann.de>"]
edition = "2018"

[dependencies]
stdweb = "0.4.20"
yew = "0.12.0"
regex = "1.3.4"
hex = "0.4.2"
log = "0.4.8"
serde = "1.0.104"